{application,elvis_core,
             [{registered,[]},
              {pkg_name,elvis_core},
              {description,"Core library for the Erlang style reviewer"},
              {vsn,"6.0.0"},
              {applications,[kernel,stdlib,katana_code,syntax_tools]},
              {modules,[elvis_code,elvis_config,elvis_core,elvis_file,
                        elvis_gitignore,elvis_project,elvis_removed_rules,
                        elvis_result,elvis_rule,elvis_ruleset,elvis_style,
                        elvis_task,elvis_text_style,elvis_utils]},
              {licenses,["Apache-2.0"]},
              {links,[{"GitHub","https://github.com/inaka/elvis_core"}]},
              {build_tools,["rebar3"]}]}.
