{application,evoq,
    [{description,"Erlang CQRS/Event Sourcing framework built on reckon-db"},
     {vsn,"1.24.2"},
     {registered,[]},
     {mod,{evoq_app,[]}},
     {applications,[kernel,stdlib,crypto,telemetry]},
     {env,
         [{store_id,default_store},
          {aggregate_defaults,
              #{hibernate_after => 60000,idle_timeout => 1800000,
                snapshot_every => 100}},
          {aggregate_partitions,4},
          {handler_defaults,#{consistency => eventual,start_from => origin}},
          {idempotency_ttl,3600000}]},
     {modules,
         [evoq_adapter,evoq_aggregate,evoq_aggregate_lifespan,
          evoq_aggregate_lifespan_default,evoq_aggregate_partition_sup,
          evoq_aggregate_registry,evoq_aggregates_sup,evoq_app,evoq_bit_flags,
          evoq_checkpoint_store,evoq_checkpoint_store_ets,evoq_command,
          evoq_command_router,evoq_consistency,evoq_dead_letter,evoq_decision,
          evoq_decision_actor,evoq_decision_partition_sup,
          evoq_decision_registry,evoq_decision_runtime,evoq_decisions_sup,
          evoq_emitter,evoq_error_handler,evoq_event,evoq_event_handler,
          evoq_event_handler_sup,evoq_event_router,evoq_event_store,
          evoq_event_type_registry,evoq_event_upcaster,evoq_execution_context,
          evoq_fact,evoq_failure_context,evoq_feedback,evoq_hope,
          evoq_idempotency,evoq_lineage,evoq_listener,evoq_memory_monitor,
          evoq_middleware,evoq_pm_instance,evoq_pm_instance_sup,
          evoq_pm_router,evoq_pm_sup,evoq_process_manager,evoq_projection,
          evoq_read_model,evoq_read_model_ets,evoq_requester,evoq_responder,
          evoq_retry_strategy,evoq_router,evoq_saga_compensation,
          evoq_snapshot_adapter,evoq_snapshot_store,evoq_state,
          evoq_store_inspector,evoq_store_subscription,
          evoq_subscription_adapter,evoq_subscriptions,evoq_sup,
          evoq_telemetry,evoq_test_assertions,evoq_type_provider]},
     {licenses,["Apache-2.0"]},
     {links,[{"GitHub","https://github.com/reckon-db-org/evoq"}]}]}.
