{application,reckon_evoq,
             [{description,"Adapter for connecting evoq to reckon-db via reckon-gater"},
              {vsn,"2.7.0"},
              {registered,[]},
              {applications,[kernel,stdlib,evoq,reckon_gater,telemetry]},
              {env,[]},
              {modules,[reckon_evoq_adapter,reckon_evoq_checkpoint_store]},
              {licenses,["Apache-2.0"]},
              {links,[{"Codeberg",
                       "https://codeberg.org/reckon-db-org/reckon-evoq"}]}]}.
